# How to Run
#
# ansible-playbook -i hosts.development -k ansible-ibm-websphere/playbooks/was-server-start.yml
#
---
- name:                     Start WAS Servers
  hosts:                    was_servers
  serial:                   1  # run sequentially
  become:                   true
  vars:
    #__profile_name:         "{{ profile_name | default('AppSrv01') }}"
    #__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
    #__servers:              "{{ servers }}"
  roles:
    - was-server-start
    
