# How to Run
#
# ansible-playbook -i hosts.development -k ansible-ibm-websphere/playbooks/was-dmgr-create-profile.yml
#
---
__profile_name:         "{{ profile_name | default('Dmgr01') }}"
__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
__default_nodename:      "{{ inventory_hostname_short }}-node"
__was_nodename:         "{{ was_nodename | default( __default_nodename ) }}"
__was_cellname:         "{{ was_cellname | default('ConnectionsCell') }}"
__was_hostname:         "{{ inventory_hostname }}"
__was_username:         "{{ was_username }}"
__was_password:         "{{ was_password }}"
__now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__logs_dir:             "{{ __was_install_location }}/logs"
__rsp_file:             "{{ __logs_dir }}/was_profile_dmgr.rsp"
__tpl_file:             "was_profile_dmgr.rsp.j2"
