---
- name:                 "Verify if pid file"
  shell:                "ps -p `cat '{{ __was_install_location }}/profiles/{{ __profile_name }}/logs/{{ item }}/{{ item }}.pid'` > /dev/null"
  register:             server_is_running
  ignore_errors:        true
  with_items:           "{{ __servers }}"

#- debug: var=server_is_running
- name:                 "Stop Servers"
  command:              "{{ __was_install_location }}/profiles/{{ __profile_name }}/bin/stopServer.sh {{ item.item }} -username {{ was_username }} -password {{ was_password }}"
  register:             cout
  changed_when:         cout.rc == 0
  when:                 item.rc == 0
  with_items:           "{{ server_is_running.results }}"
