---
- name:                 "Verify if pid file"
  shell:                "ps -p `cat '{{ __was_install_location }}/profiles/{{ __profile_name }}/logs/nodeagent/nodeagent.pid'` > /dev/null"
  register:             nodeagent_is_running
  ignore_errors:        true

- name:                 "Stop Node Agent"
  command:              "{{ __was_install_location }}/profiles/{{ __profile_name }}/bin/stopNode.sh  -username {{ was_username }} -password {{ was_password }}"
  register:             cout
  changed_when:         cout.rc == 0
  #changed_when:        ( start.stdout.find('open for e-business') != -1)
  when:                 nodeagent_is_running.rc == 0
