# check defined variables
---
- name: ihs_password should be defined
  assert:
    that:
    - ihs_password is defined and ihs_password != ''
    msg: "Set the value of 'ihs_password' in the inventory file."
