---
- name:          "Is dmgr Running?"
  shell:         "ps -p `cat '{{ __was_install_location }}/profiles/{{ __profile_name }}/logs/dmgr/dmgr.pid'` > /dev/null"
  register:      dmgr_is_running
  ignore_errors: true

- name:          "Start Dmgr"
  command:       "{{ __was_install_location }}/profiles/{{ __profile_name }}/bin/startManager.sh"
  register:      dmgr_start
  changed_when:  dmgr_start.rc == 0
  failed_when:   dmgr_start.rc != 0
  when:          dmgr_is_running.rc != 0

- name:          "Is dmgr Running?"
  shell:         "ps -p `cat '{{ __was_install_location }}/profiles/{{ __profile_name }}/logs/dmgr/dmgr.pid'` > /dev/null"
  register:      cout
  ignore_errors: true
  when:          (dmgr_start.rc is defined) and (dmgr_start.rc == 0)

- name:          Wait 60 seconds for DMGR to activate
  pause:
    seconds:     60
  when:          (dmgr_start.rc is defined) and (dmgr_start.rc == 0)
