---
- name:                 "Verifiy if Profile already exists"
  stat:
    path:               "{{ __was_install_location }}/profiles/{{ __profile_name }}"
  register:             profile_already_exists

- name:                 Verify if pid file
  shell:                ps -p `cat "{{ __was_install_location }}/profiles/{{ __profile_name }}/logs/dmgr/dmgr.pid"`
  register:             dmgr_is_running
  ignore_errors:        true

- name:                 "Generate Response file"
  template:
    src:                "{{ __tpl_file }}"
    dest:               "{{ __rsp_file }}"

- name:                 "Add TLS Signer Certificate for AD to Cell Default Trust Store"
  command:
    chdir={{ __bin_dir }}
    {{ __bin_dir }}/wsadmin.sh -lang jython -port {{ __dmgr_soap_port }} -username {{ __was_username }} -password {{ __was_password }} -f {{ __rsp_file }} {{ __cluster_name }}
  register:             cout
  changed_when:         cout.rc == 0
  #changed_when:         ( cout.stdout.find('INSTCONFSUCCESS') != -1)


    