---
- name:                 "Generate Response file"
  template:
    src:                "{{ __tpl_file }}"
    dest:               "{{ __rsp_file }}"

- name:                 "Create Profile"
  command:              "{{ __was_install_location }}/bin/manageprofiles.sh -response {{ __rsp_file }}"
  register:             cout
  changed_when:         ( cout.stdout.find('INSTCONFSUCCESS') != -1)
  failed_when:          ( cout.stdout.find('INSTCONFFAILED') != -1)
