---
__profile_name:         "{{ profile_name | default('Dmgr01') }}"
__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
__default_nodename:      "{{ inventory_hostname_short }}-node"
__was_nodename:         "{{ was_nodename | default( __default_nodename ) }}"
__was_cellname:         "{{ was_cellname | default('ConnectionsCell') }}"
__was_username:         "{{ was_username }}"
__was_password:         "{{ was_password }}"
__dmgr_soap_port:       "{{ dmgr_soap_port | default('8879')}}"
__now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__bin_dir:              "{{ __was_install_location }}/profiles/{{ __profile_name }}/bin"
__rsp_file:             "{{ __bin_dir }}/was_config_dmgr_jvm.py"
__tpl_file:             "was_config_dmgr_jvm.py.j2"
__success_file:         "{{ __bin_dir }}/was-dmgr-config-jvm.success"