---
__profile_name:         "{{ profile_name | default('Dmgr01') }}"
__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
__was_username:         "{{ was_username }}"
__was_password:         "{{ was_password }}"
__dmgr_soap_port:       "{{ dmgr_soap_port | default('8879')}}"
__now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__bin_dir:              "{{ __was_install_location }}/profiles/{{ __profile_name }}/bin"
__rsp_file:             "{{ __bin_dir }}/was_import_tls_cert.py"
__tpl_file:             "was_import_tls_cert.py.j2"
__success_file:         "{{ __bin_dir }}/was-dmgr-import-tls-cert.success"
