---
- name:                 "Verifiy if Profile already exists"
  stat:
    path:               "{{ __was_install_location }}/profiles/{{ __profile_name }}/logs/nodeagent"
  register:             profile_already_exists

- name:                 Is Standalone?
  set_fact:
    __tpl_file:         "was_profile_node_unmanaged.rsp.j2"
  when:                 ( __is_standalone )

- name:                 "Generate Response file"
  template:
    src:                "{{ __tpl_file }}"
    dest:               "{{ __rsp_file }}"
  when:                 profile_already_exists.stat.exists != true

- name:                 "Create Was Profile"
  command:              "{{ __was_install_location }}/bin/manageprofiles.sh -response {{ __rsp_file }}"
  register:             cout
  changed_when:         ( cout.stdout.find('INSTCONFSUCCESS') != -1)
  failed_when:          ( cout.stdout.find('INSTCONFFAILED') != -1)
  when:                 profile_already_exists.stat.exists != true
