# check_openshift.yml
---
- name: iim_repository_url should be defined
  assert:
    that:
    - iim_repository_url is defined and iim_repository_url != ''
    msg: "Set the value of 'iim_repository_url' in the inventory file."
