---
- name:                 "Verifiy if Profile already exists"
  stat:
    path:               "{{ __was_install_location }}/profiles/{{ __profile_name }}"
  register:             profile_already_exists

- name:                 Verify if pid file
  shell:                ps -p `cat "{{ __was_install_location }}/profiles/{{ __profile_name }}/logs/dmgr/dmgr.pid"`
  register:             dmgr_is_running
  ignore_errors:        true

- name:                 "Verifiy if Application Security is already configured"
  stat:
    path:               "{{ __success_file }}"
  register:             app_sec_already_configured
  when:                 profile_already_exists.stat.exists == true

- name:                 "Enable Application Security"
  include_tasks:        enable_app_sec.yml
  when:                 app_sec_already_configured.stat.exists == false